# Generated by Django 2.0.13 on 2019-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255, verbose_name='属于哪个Zone')),
                ('host', models.CharField(max_length=255, verbose_name='二级域名')),
                ('dns_type', models.CharField(max_length=16, null=True, verbose_name='DNS类型')),
                ('data', models.CharField(max_length=255, verbose_name='对应的IP/值')),
                ('ttl', models.IntegerField(default=60, verbose_name='生存周期时间')),
                ('mx_priority', models.IntegerField(default=None)),
                ('view', models.SmallIntegerField(choices=[(0, 'Telecom'), (1, 'Unicom'), (2, 'CMCC'), (3, 'other')], default=3, verbose_name='属于哪个公司')),
                ('priority', models.IntegerField(default=255)),
                ('refresh', models.IntegerField(default=28800)),
                ('retry', models.IntegerField(default=14400)),
                ('expire', models.IntegerField(default=86400)),
                ('minimum', models.IntegerField(default=86400)),
                ('serial', models.IntegerField(default=0)),
                ('resp_person', models.CharField(default='test.com', max_length=64)),
                ('primary_ns', models.CharField(default='ns.test.com.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='abc.com', max_length=255, verbose_name='属于哪个Zone')),
            ],
        ),
    ]
